import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TanStackProvider } from "@/provider/tanstack-provider"
import { NextThemeProvider } from "@/provider/theme-provider"
import Footer from "@/components/footer";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextThemeProvider>
          <TanStackProvider>
            <SidebarProvider>
              <AppSidebar/>
            <SidebarInset>
              <SidebarTrigger className="absolute top-2 left-2 z-50" />
              <main className="min-h-screen">
                 <Toaster/>
              {children}
              </main>
              <Footer />
            </SidebarInset>
            </SidebarProvider>
          </TanStackProvider>
        </NextThemeProvider>
      </body>
    </html>
  );
}
