import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TanStackProvider } from "@/provider/tanstack-provider"
import { NextThemeProvider } from "@/provider/theme-provider"
import Footer from "@/components/footer";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Toaster } from "@/components/ui/sonner"
import { Separator } from "@/components/ui/separator"
import { DynamicBreadcrumb } from "@/components/dynamic-breadcrumb"
import Toggle from "@/components/toggle-theme";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextThemeProvider>
          <TanStackProvider>
            <SidebarProvider>
              <AppSidebar />
              <SidebarInset >
                <header className="flex border border-b-natural-50 h-12  shrink-0 items-center justify-between pr-2 gap-2 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12 sticky top-0">
                  <div className="flex items-center gap-2 px-2 sm:px-4">
                    <SidebarTrigger className="-ml-1" />
                    <Separator
                      orientation="vertical"
                      className="mr-1 sm:mr-2 dark:bg-accent data-[orientation=vertical]:h-4"
                    />
                    <DynamicBreadcrumb />
                  </div>
                  <Toggle/>
                </header>
                <main className="min-h-screen flex flex-1 flex-col  pt-0">
                  <Toaster />
                  {children}
                </main>
                <Footer />
              </SidebarInset>
            </SidebarProvider>
          </TanStackProvider>
        </NextThemeProvider>
      </body>
    </html>
  );
}
